### ISSUE TITLE
`UnhandledPromiseRejectionWarning` + traceback when trying to open a database

### ISSUE THREAD

**Issue by bradenbest** [derhuerst/leveldb-editor#3]
So I got it to work, as discussed on #2. Upon starting it with an indexeddb directory (chromium), I get the following error/warning/traceback:

    $ ~/node_modules/leveldb-editor/cli.js whatever
    no entries
    whatever(node:5861) UnhandledPromiseRejectionWarning: OpenError: IO error: lock whatever/LOCK: Resource temporarily unavailable
        at /home/braden/node_modules/levelup/lib/levelup.js:91:23
        at /home/braden/node_modules/abstract-leveldown/abstract-leveldown.js:41:14
        at /home/braden/node_modules/deferred-leveldown/deferred-leveldown.js:20:21
        at /home/braden/node_modules/abstract-leveldown/abstract-leveldown.js:41:14
        at /home/braden/node_modules/abstract-leveldown/abstract-leveldown.js:41:14
    (node:5861) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated 
    either by throwing inside of an async function without a catch block, or by rejecting a promise which 
    was not handled with .catch(). (rejection id: 1)
    (node:5861) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the 
    future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit 
    code.

I can immediately see that the program doesn't see any entries in the database. The error isn't exactly fatal, as pressing `q` cleanly quits the program.

I have no reason to believe that this isn't the correct type of database, as it was generated by chromium, and is an indexeddb database. Here's ls:

    $ ls whatever
    000003.log  CURRENT  gamedata-https_v6p9d9t4-20180430-1339.tar  LOCK  LOG  LOG.old  MANIFEST-000001

All the stuff is there, plus a tar backup of the data (and @derhuerst , yes I have tried extracting said tar into the other directory. No, it doesn't work. It seems the directory name is baked into 000003.log as part of an annoying cross-origin policy).

Me personally, I don't care any more. I already gave up on my proverbial XY problem. I knew it was a crapshoot going in, and just wanted to try. Frankly, I'm now sick and tired of indexeddb, and don't want anything more to do with it. The reason I'm posting this issue, aside from closure, is because there seems to be a bug, and you should be made aware of it. As the user, I feel it's my duty to report it.

Sorry for the trouble, @derhuerst . I appreciate you graciously putting up with my bullshit and being patient with me. I can be a dick when I'm angry, and I shouldn't have taken it out on you. It was un called for, and I sincerely apologize. I hope I at least helped you make your program the best it can be.

**Comment by derhuerst** [comment]
> Upon starting it with an indexeddb directory (chromium), I get the following error/warning/traceback:
>
> ```
> $ ~/node_modules/leveldb-editor/cli.js whatever
> UnhandledPromiseRejectionWarning: OpenError: IO error: lock whatever/LOCK: Resource temporarily unavailable
> ```

*The error itself* is related to the database you're trying to inspect.

But the fact that `leveldb-editor` doesn't properly catch, log the error and exit with `1`, is indeed a bug.

**Comment by derhuerst** [comment]
I've published `leveldb-editor@0.1.3` that should mitigate the error logging issue.

**Comment by derhuerst** [comment]
> I have no reason to believe that this isn't the correct type of database, as it was generated by chromium, and is an indexeddb database.

Try [this one](https://github.com/derhuerst/leveldb-editor/files/1966936/example.ldb.zip), it should work.

> Me personally, I don't care any more. I already gave up on my proverbial XY problem. I knew it was a crapshoot going in, and just wanted to try. Frankly, I'm now sick and tired of indexeddb, and don't want anything more to do with it.

I can't understand this. 😉

**Comment by bradenbest** [comment]
Umm... on both the directory I was trying, and the `example.ldb` directory you sent me, the program crashes with the same error:

    $ npx leveldb-editor example.ldb/
    Identifier 'noop' has already been declared
    $ echo $?
    1
