### ISSUE TITLE
Identifier 'noop' has already been declared / exit 1

### ISSUE THREAD

**Issue by bradenbest** [derhuerst/leveldb-editor#4]
Mentioned on #3. Seems like a different issue. Here's the log again:

    $ npx leveldb-editor example.ldb/
    Identifier 'noop' has already been declared
    $ echo $?
    1

Actually, the program just crashes regardless:

    $ npx leveldb-editor
    Identifier 'noop' has already been declared

**Comment by derhuerst** [comment]
Fixed as of `leveldb-editor@0.1.4`.

**Comment by bradenbest** [comment]
I did try `v0.1.2` with it, and it worked (0.1.4 does as well). However, I no longer understand the point of your program. The only operation I can seem to make it do is delete a key, no add or edit functionality (the project is named "leveldb-editor"). And on top of that, the UI/UX isn't very good. I'm not referring to it being ncurses, I'm referring to the fact that changes (I.e. deletions) are instantly applied, instead of stored in a buffer and written on-exit (so that there's a chance to exit *without* writing), and without an `undo` operation, that means that once you press d or Backspace on your sweep across the keyboard to find a button that does something, you'll irreversibly delete a key. Imagine if that happened in Vim or Emacs.

I did also try hitting `:`, but I'm unsure if the program actually *has* a command mode, because while a blue `:` appeared in place of the database name, seemingly ready to accept commands, I tried typing and nothing appeared next to the colon. I tried `:help`, and nothing happened. In fact, the only characters that appear next to the colon when I hit them are keys that the program accepts in its nomal mode. `qdjk`. Pressing enter seems to apply said commands in order, as a queue, but it's inconsistent. With one db key left, and the buffer having a `d` at the beginning, pressing enter made the program delete the last key, the `d` disappeared, and now the program won't do anything when I hit enter. The only option left is to backspace entirely out of the "command queue" mode and hit `q` in normal mode.

The fact that `d` is one of four keys that will show on said mode further supports my theory that delete is the only available operation.

Investigating the commit history also lines up with this, which means this project must be in alpha. However, before I came along and started posting issues, the last commit was made in August 2017, meaning several months passed before anything in this project was changed.

Am I right in assuming this is a dead/abandoned project?

**Comment by bradenbest** [comment]
@derhuerst, I just read your final reply on #2. I would suggest putting a notice on your readme that says this is in alpha development, is abandoned (if that's the case), and a list of the features (currently: command queue and delete), etc. That way you won't get any more jerks like me wasting your time, because we'll know from the get-go that this probably isn't the solution to our problem and that the dev has better things to do.

I know that probably sounds facetious (especially the "has better things to do"), but I assure you I'm 100% serious. I'm not throwing shade, or being sarcastic, or passive-aggressive, or implying that you should feel bad about abandoning this project, or anything like that. I genuinely feel bad about the way I handled this, and don't want to waste any more of your time. And I'm saying that if this project is abandoned, I completely understand.

**Comment by derhuerst** [comment]
> And on top of that, the UI/UX isn't very good. [...] I'm referring to the fact that changes (I.e. deletions) are instantly applied, instead of stored in a buffer and written on-exit (so that there's a chance to exit without writing), and without an undo operation, that means that once you press d or Backspace on your sweep across the keyboard to find a button that does something, you'll irreversibly delete a key. Imagine if that happened in Vim or Emacs.

Don't consider it a text editor, consider it a db editor. They often don't have an undo functionality.

But yeah, the UX could be a lot better.

> I would suggest putting a notice on your readme that says this is in alpha development, is abandoned (if that's the case), and a list of the features (currently: command queue and delete), etc.

Will do that.
